export const presetLists1 = {
    'Prefix Brandables': ['a', 'ab', 'ac', 'acu', 'ada', 'adv', 'aero', 'af', 'ag', 'agro', 'ah', 'ai', 'aj', 'ak', 'al', 'ala', 'alfa', 'ali', 'alt', 'alter', 'am', 'ama', 'ami', 'amp', 'an', 'ana', 'ani', 'ant', 'anti', 'any', 'ap', 'aqua', 'ar', 'as', 'at', 'aus', 'av', 'ava', 'aw', 'ax', 'az', 'ba', 'bb', 'bc', 'bd', 'be', 'bel', 'bf', 'bi', 'bl', 'bo', 'br', 'bu', 'by', 'ca', 'ch', 'chi', 'ci', 'cine', 'cl', 'co', 'comm', 'con', 'cor', 'cosmo', 'cr', 'cre', 'crea', 'cu', 'cy', 'cyber', 'da', 'de', 'di', 'dia', 'digi', 'dis', 'do', 'dom', 'dr', 'du', 'duo', 'dy', 'dyna', 'ea', 'ec', 'econo', 'ed', 'eg', 'el', 'electro', 'em', 'en', 'epi', 'eq', 'equi', 'es', 'et', 'ex', 'exo', 'fa', 'fe', 'fi', 'fin', 'flex', 'flexi', 'flo', 'fo', 'fr', 'fu', 'ga', 'ge', 'glo', 'go', 'gr', 'ha', 'hd', 'he', 'heli', 'hi', 'ho', 'holo', 'hy', 'hyper', 'if', 'im', 'immo', 'in', 'indi', 'indo', 'infini', 'inno', 'int', 'intelli', 'inter', 'into', 'intra', 'iq', 'ir', 'is', 'it', 'ja', 'je', 'jo', 'ju', 'ka', 'ku', 'ky', 'li', 'lo', 'lu', 'ly', 'ma', 'macro', 'mag', 'mai', 'mar', 'mas', 'maxi', 'me', 'mem', 'meta', 'mi', 'mid', 'mo', 'mobi', 'mod', 'mon', 'mono', 'moto', 'mu', 'multi', 'my', 'mx', 'na', 'nat', 'navi', 'ne', 'neo', 'neu', 'neuro', 'nex', 'ni', 'no', 'nor', 'nu', 'ob', 'oc', 'of', 'og', 'ok', 'ol', 'omni', 'on', 'op', 'opti', 'or', 'os', 'out', 'ox', 'oz', 'pa', 'pe', 'penta', 'per', 'ph', 'photo', 'pi', 'po', 'poly', 'pr', 'pre', 'proto', 'pu', 'qi', 're', 'ri', 'ro', 'ru', 'sa', 'sci', 'se', 'sh', 'si', 'so', 'st', 'sub', 'super', 'sy', 'sym', 'syn', 'sync', 'ta', 'th', 'ti', 'to', 'tra', 'tr', 'trans', 'tu', 'ty', 'ui', 'ultra', 'un', 'uni', 'up', 'us', 'va', 'vc', 'velo', 'veri', 'vet', 'vo', 'vr', 'vu', 'wa', 'we', 'why', 'wi', 'with', 'wo', 'xy', 'ya', 'yo', 'za'],
    // 1) Codes & Acronyms
'Codes & Acronyms': [
  'ceo', 'cms', 'cpa', 'crm', 'css', 'dns', 'mvp', 'mx', 'pos', 'seo',
  'sim', 'tek', 'tel', 'tele', 'txt', 'url', 'usa', 'vid', 'vids', 'vip',
],

// 2) People & Roles
'People & Roles': [
  'admin', 'agent', 'artist', 'attorney', 'broker', 'captain', 'champion', 'chef',
  'coach', 'designer', 'doctor', 'gamer', 'host', 'hunter', 'investor', 'lawyer',
  'leader', 'nurse', 'pilot', 'player', 'pro', 'prof', 'professional', 'student',
  'teacher', 'trainer', 'tutor', 'vendor', 'worker', 'writer', 'writers',
],

// 3) Action Verbs
'Action Verbs': [
  'add', 'aim', 'answer', 'ask', 'auction', 'barter', 'base', 'beam', 'beat', 'bid', 'bill', 'blog',
  'book', 'boom', 'boost', 'brew', 'bridge', 'build', 'buy', 'call', 'camp', 'campaign', 'cast',
  'catch', 'change', 'chase', 'chat', 'check', 'choose', 'click', 'climb', 'clip', 'code', 'compare',
  'complete', 'connect', 'contact', 'control', 'cook', 'copy', 'cover', 'create', 'credit', 'cross',
  'cruise', 'cut', 'cycle', 'dance', 'dash', 'date', 'deal', 'design', 'dial', 'dig', 'direct',
  'discover', 'dive', 'download', 'dream', 'dress', 'drink', 'drive', 'drift', 'drop', 'eat', 'edit',
  'email', 'enjoy', 'enter', 'excel', 'exchange', 'explore', 'express', 'feed', 'feel', 'fight',
  'file', 'film', 'find', 'fire', 'fit', 'fix', 'flash', 'flip', 'flow', 'fly', 'follow', 'forge',
  'form', 'frame', 'free', 'friend', 'front', 'fund', 'fuse', 'grow', 'guide', 'hack', 'hand', 'have',
  'heal', 'help', 'hire', 'host', 'hunt', 'ignite', 'imagine', 'impact', 'index', 'inspire', 'invest',
  'join', 'jump', 'keep', 'kick', 'lead', 'learn', 'lease', 'lend', 'like', 'link', 'list', 'live',
  'load', 'lock', 'look', 'loop', 'love', 'mail', 'make', 'manage', 'map', 'market', 'match', 'meet',
  'message', 'move', 'pack', 'paint', 'park', 'partner', 'pass', 'pay', 'pick', 'pin', 'ping', 'pitch',
  'place', 'plan', 'play', 'post', 'power', 'practice', 'print', 'profile', 'program', 'project',
  'promo', 'propel', 'purchase', 'race', 'rank', 'reach', 'read', 'record', 'recycle', 'reg', 'relay',
  'rent', 'report', 'rescue', 'research', 'review', 'reward', 'ride', 'ring', 'run', 'save', 'scan',
  'search', 'secure', 'see', 'seed', 'seek', 'select', 'sell', 'send', 'serve', 'set', 'share', 'ship',
  'shop', 'show', 'sign', 'sing', 'sleep', 'slide', 'smile', 'snap', 'speak', 'speed', 'spin', 'splash',
  'spot', 'stack', 'stage', 'start', 'steam', 'step', 'stop', 'store', 'stream', 'study', 'style',
  'surf', 'swap', 'swing', 'switch', 'tag', 'take', 'talk', 'teach', 'test', 'think', 'thrive',
  'ticket', 'tip', 'touch', 'tour', 'track', 'trade', 'train', 'transfer', 'transport', 'travel',
  'trend', 'trick', 'trip', 'tune', 'tweet', 'type', 'update', 'upload', 'value', 'vote', 'walk',
  'wash', 'watch', 'wear', 'win', 'wish', 'work', 'wrap', 'write',
],
// 4) Tech & Web
'Tech & Web': [
  'ai', 'api', 'app', 'apps', 'bit', 'block', 'bot', 'chat', 'cloud', 'code',
  'crypto', 'cyber', 'data', 'dev', 'dns', 'download', 'drive', 'email', 'file',
  'git', 'hack', 'host', 'http', 'iot', 'link', 'login', 'net', 'node', 'online',
  'os', 'pixel', 'platform', 'plugin', 'robot', 'script', 'server', 'site', 'sms',
  'software', 'source', 'stack', 'store', 'stream', 'tech', 'tools', 'url', 'user',
  'video', 'web', 'wifi',
],

// 5) Biz & Money
'Biz & Money': [
  'account', 'ads', 'agency', 'bank', 'bids', 'biz', 'brand', 'budget', 'bundle',
  'buy', 'capital', 'card', 'cash', 'checkout', 'clients', 'club', 'commerce',
  'company', 'consult', 'consulting', 'corp', 'cost', 'coupon', 'credit', 'deal',
  'deals', 'debit', 'donate', 'earn', 'ecom', 'equity', 'escrow', 'fees', 'finance',
  'fund', 'funds', 'group', 'hire', 'income', 'inc', 'invoice', 'invest', 'llc',
  'loan', 'market', 'money', 'offer', 'partner', 'pay', 'payments', 'pricing',
  'profit', 'promo', 'quote', 'rate', 'rent', 'return', 'revenue', 'sale', 'save',
  'sell', 'service', 'shop', 'solution', 'startup', 'store', 'stripe', 'subscribe',
  'subs', 'supply', 'tax', 'team', 'trade', 'value', 'wallet', 'worth',
],

// 6) Media & Creative
'Media & Creative': [
  'ad', 'ads', 'album', 'art', 'artist', 'audio', 'blog', 'books', 'brand', 'camera',
  'cast', 'cinema', 'clip', 'content', 'creative', 'design', 'documentary', 'draw',
  'edit', 'film', 'gallery', 'gif', 'graphics', 'image', 'illustration', 'logo',
  'media', 'meme', 'mix', 'music', 'paint', 'photo', 'photography', 'pod', 'poster',
  'print', 'publish', 'radio', 'record', 'reel', 'remix', 'screen', 'share', 'shoot',
  'show', 'sketch', 'snap', 'song', 'sound', 'stream', 'style', 'tune', 'tv', 'video',
  'vids', 'visual', 'voice', 'vlog', 'write',
],
// 7) Lifestyle & Wellness
'Lifestyle & Wellness': [
  'balance', 'beauty', 'body', 'care', 'clean', 'coach', 'detox', 'diet', 'doctor',
  'energy', 'essence', 'fit', 'fitness', 'food', 'fresh', 'glow', 'gym', 'happy',
  'health', 'heal', 'heart', 'home', 'life', 'lifestyle', 'live', 'love', 'mood',
  'natural', 'peace', 'relax', 'reset', 'self', 'skin', 'sleep', 'smile', 'spa',
  'spirit', 'strong', 'tone', 'vibe', 'vital', 'vitamin', 'well', 'wellness', 'yoga',
],

// 8) Product & Commerce
'Product & Commerce': [
  'bag', 'bar', 'bed', 'bell', 'box', 'bundle', 'buy', 'cart', 'chair', 'clock',
  'coffee', 'cookie', 'cup', 'cushion', 'deal', 'desk', 'device', 'dish', 'drink',
  'fan', 'food', 'fridge', 'furniture', 'gift', 'grill', 'item', 'jar', 'kettle',
  'kit', 'lamp', 'lid', 'mattress', 'mirror', 'mug', 'pack', 'pan', 'pillow', 'plate',
  'product', 'rug', 'sale', 'shelf', 'shoes', 'sofa', 'spoon', 'stool', 'store',
  'stuff', 'table', 'tablet', 'tools', 'toys', 'tv', 'vacuum', 'watch', 'wear',
],

// 9) Location & Travel
'Location & Travel': [
  'abroad', 'airport', 'area', 'beach', 'bridge', 'camp', 'capital', 'car', 'city',
  'coast', 'country', 'cruise', 'destination', 'explore', 'flight', 'global', 'go',
  'guide', 'highway', 'holiday', 'hotel', 'island', 'journey', 'lane', 'local',
  'location', 'lodge', 'map', 'motel', 'mountain', 'nation', 'outdoors', 'passport',
  'place', 'road', 'route', 'ship', 'spot', 'state', 'stay', 'street', 'tour',
  'tourism', 'town', 'traffic', 'train', 'travel', 'trip', 'vacation', 'visit', 'way',
  'world',
],
// 10) General Nouns
'General Nouns': [
  'access', 'action', 'answer', 'base', 'boost', 'box', 'build', 'bundle', 'buzz',
  'center', 'click', 'code', 'core', 'deal', 'engine', 'feed', 'file', 'flow', 'gear',
  'group', 'hub', 'idea', 'item', 'kit', 'line', 'link', 'list', 'load', 'loop',
  'market', 'match', 'mode', 'move', 'name', 'net', 'offer', 'option', 'pack', 'path',
  'place', 'plan', 'point', 'post', 'power', 'reach', 'report', 'result', 'sale',
  'score', 'search', 'set', 'shift', 'shop', 'signal', 'site', 'slot', 'source',
  'stack', 'start', 'step', 'store', 'stream', 'style', 'system', 'task', 'team',
  'tool', 'top', 'track', 'trade', 'trend', 'trip', 'turn', 'type', 'unit', 'user',
  'value', 'view', 'voice', 'way', 'web', 'word', 'zone',
],

// 11) Adjectives & Modifiers
'Adjectives & Modifiers': [
  'active', 'alpha', 'amazing', 'best', 'better', 'bold', 'bright', 'brilliant',
  'clean', 'clear', 'clever', 'cool', 'daily', 'deep', 'direct', 'easy', 'eco',
  'epic', 'fast', 'first', 'free', 'fresh', 'full', 'future', 'global', 'gold',
  'good', 'great', 'green', 'happy', 'hard', 'high', 'hot', 'infinite', 'instant',
  'joy', 'light', 'local', 'loud', 'lucky', 'main', 'major', 'max', 'mega', 'mini',
  'modern', 'more', 'nano', 'new', 'next', 'now', 'only', 'open', 'prime', 'pro',
  'pure', 'quick', 'real', 'safe', 'secret', 'secure', 'simple', 'smart', 'solid',
  'speed', 'steady', 'strong', 'super', 'top', 'true', 'turbo', 'ultra', 'vivid',
  'wide', 'wild', 'wise', 'young', 'zero',
],

// 12) People & Roles
'Users & Roles': [
  'admin', 'agent', 'artist', 'author', 'boss', 'ceo', 'champ', 'chief', 'citizen',
  'client', 'coder', 'coach', 'consultant', 'creator', 'crew', 'customer', 'dev',
  'doctor', 'editor', 'engineer', 'expert', 'fan', 'founder', 'friend', 'gamer',
  'geek', 'guest', 'guru', 'hacker', 'hero', 'host', 'human', 'influencer', 'kid',
  'king', 'lawyer', 'leader', 'maker', 'manager', 'member', 'mentor', 'mod', 'ninja',
  'officer', 'owner', 'partner', 'people', 'player', 'president', 'pro', 'reader',
  'recruiter', 'rider', 'seller', 'senior', 'shark', 'student', 'teacher', 'team',
  'tech', 'user', 'veteran', 'voter', 'worker', 'writer',
],

  'US States': ['AK', 'AL', 'Alabama', 'Alaska', 'AR', 'Arizona', 'Arkansas', 'AZ', 'CA', 'Cali', 'California', 'CO',
  'Colorado', 'Connecticut', 'CT', 'DE', 'Delaware', 'FL', 'Florida', 'GA', 'Georgia', 'HI', 'Hawaii',
  'IA', 'ID', 'Idaho', 'IL', 'Illinois', 'IN', 'Indiana', 'Iowa', 'KS', 'Kansas', 'Kentucky', 'KY',
  'LA', 'Louisiana', 'MA', 'Maine', 'Maryland', 'Mass', 'Massachusetts', 'MD', 'ME', 'MI', 'Michigan',
  'Minnesota', 'Mississippi', 'Missouri', 'MN', 'MO', 'MS', 'MT', 'Montana', 'NC', 'ND', 'NE', 'Nebraska',
  'Nevada', 'NewHampshire', 'NewJersey', 'NewMexico', 'NewYork', 'NH', 'NJ', 'NM', 'NorthCarolina',
  'NorthDakota', 'NY', 'OH', 'Ohio', 'OK', 'Oklahoma', 'OR', 'Oregon', 'PA', 'Pennsylvania', 'RI',
  'RhodeIsland', 'SC', 'SD', 'SouthCarolina', 'SouthDakota', 'TN', 'Tennessee', 'Tex', 'Texas', 'TX',
  'UT', 'Utah', 'VA', 'Vegas', 'Vermont', 'Virginia', 'VT', 'WA', 'Washington', 'WestVirginia', 'WI',
  'Wisconsin', 'WV', 'WY', 'Wyoming'
],
'US Counties': [
  'Adams', 'Alameda', 'Albany', 'Albuquerque', 'Allegheny', 'Allen', 'Anchorage', 'Anderson',
  'AnneArundel', 'Anoka', 'Arapahoe', 'Ashtabula', 'Atlantic', 'Baltimore', 'BatonRouge', 'Bell',
  'Bergen', 'Berkeley', 'Berks', 'Bernalillo', 'Bexar', 'Boulder', 'Brazoria', 'Brevard', 'Bronx',
  'Broome', 'Broward', 'Bucks', 'Buncombe', 'Burlington', 'Butler', 'Cabarrus', 'Caddo', 'Calcasieu',
  'Camden', 'Cameron', 'CapeMay', 'CarsonCity', 'Cascade', 'Cass', 'Champaign', 'Charleston',
  'Charlotte', 'Chatham', 'Chelan', 'Chester', 'Christian', 'Clark', 'Clermont', 'Cobb', 'Collier',
  'Collin', 'ColoradoSprings', 'Columbia', 'Columbus', 'ContraCosta', 'Cook', 'Coweta', 'Cowlitz',
  'Cumberland', 'Cuyahoga'
],
'US Cities': [
  'Abilene', 'Akron', 'Albuquerque', 'Alexandria', 'Allentown', 'Amarillo', 'Anaheim', 'AnnArbor',
  'Anchorage', 'Antioch', 'Arlington', 'Arvada', 'Athens', 'Atlanta', 'ATL', 'Augusta', 'Aurora',
  'Austin', 'Bakersfield', 'Baltimore', 'BatonRouge', 'Beaumont', 'Bellevue', 'Berkeley', 'Billings',
  'Birmingham', 'Boise', 'Boston', 'Boulder', 'Bridgeport', 'Brownsville', 'Buffalo', 'Burbank',
  'Cambridge', 'CapeCoral', 'Carrollton', 'Cary', 'CedarRapids', 'Centennial', 'Chandler',
  'Charleston', 'Charlotte', 'Chattanooga', 'Chesapeake', 'Chi', 'Chicago', 'ChulaVista', 'Cincinnati',
  'Clarksville', 'Clearwater', 'Cleveland', 'CollegeStation', 'ColoradoSprings', 'Columbia', 'Columbus',
  'Concord', 'CoralSprings', 'Corona', 'CorpusChristi', 'CostaMesa', 'Dallas', 'DalyCity', 'Davenport',
  'Davie', 'Dayton', 'DC', 'Denton', 'Denver', 'DesMoines', 'Detroit', 'Downey', 'Durham'
]
      
  };
  
  export const presetLists2 = {
    'Suffix Brandables': [
      'a', 'ab', 'ac', 'ad', 'ada', 'adv', 'aero', 'af', 'ag', 'agro', 'ah', 'ai', 'aj', 'ak', 'al', 'ala', 'alfa', 'ali', 'alt', 'alter',
      'am', 'ama', 'ami', 'amp', 'an', 'ana', 'and', 'ani', 'ant', 'any', 'ap', 'aqua', 'ar', 'as', 'at', 'av', 'aw', 'ax', 'az', 'ba', 'bb',
      'bc', 'bd', 'be', 'bf', 'bi', 'bl', 'bo', 'br', 'bu', 'by', 'ca', 'ce', 'ch', 'ci', 'cl', 'co', 'con', 'cor', 'cr', 'cre', 'crea', 'cs',
      'ct', 'cu', 'cy', 'da', 'de', 'di', 'dia', 'digi', 'dis', 'do', 'dom', 'dr', 'du', 'duo', 'dy', 'ea', 'ec', 'econo', 'ed', 'ee', 'eg',
      'el', 'electro', 'em', 'en', 'ent', 'eo', 'ep', 'epi', 'eq', 'equi', 'er', 'ers', 'es', 'et', 'ex', 'exo', 'ey', 'ez', 'fa', 'fe', 'fi',
      'for', 'fr', 'fs', 'fu', 'fy', 'ga', 'ge', 'glo', 'go', 'gr', 'ha', 'hd', 'he', 'hi', 'ho', 'hq', 'hy', 'ia', 'ian', 'ic', 'id', 'ie',
      'ies', 'ify', 'ii', 'il', 'im', 'in', 'io', 'ion', 'ip', 'iq', 'ir', 'is', 'ish', 'ism', 'it', 'its', 'ity', 'ium', 'ix', 'ize', 'je',
      'ji', 'jo', 'ju', 'ka', 'ko', 'ku', 'ky', 'la', 'le', 'li', 'lo', 'ls', 'lu', 'ly', 'ma', 'ms', 'mu', 'mx', 'na', 'nc', 'ne', 'ng',
      'ngo', 'ni', 'nj', 'no', 'ns', 'nt', 'ny', 'nz', 'ob', 'oc', 'of', 'og', 'ok', 'ol', 'om', 'on', 'oo', 'op', 'or', 'os', 'out', 'ow',
      'ox', 'oz', 'pa', 'pc', 'pe', 'ph', 'pi', 'pl', 'pm', 'po', 'pr', 'pre', 'pro', 'ps', 'pt', 'ra', 'rc', 're', 'ri', 'ro', 'rr', 'rs',
      'ru', 'ry', 'sa', 'sc', 'se', 'sh', 'si', 'so', 'sp', 'ss', 'st', 'su', 'sy', 'ta', 'tc', 'te', 'ter', 'th', 'that', 'the', 'ti', 'to',
      'tr', 'ts', 'tt', 'tu', 'tv', 'ty', 'uk', 'um', 'un', 'up', 'ur', 'us', 'va', 'vc', 've', 'vi', 'vo', 'vr', 'vu', 'wa', 'we', 'who',
      'why', 'wi', 'wo', 'xs', 'xx', 'ya', 'yo', 'ys', 'za', 'ze', 'zi', 'zo', 'zy', 'zz'
    ],

  
'Suffix Words': [
  'ace', 'access', 'account', 'action', 'active', 'add', 'addict', 'admin', 'ads', 'advantage', 
  'adventure', 'advice', 'advisor', 'advisors', 'again', 'age', 'agency', 'agent', 'agents', 'air',
  'alert', 'alerts', 'alive', 'all', 'alley', 'ally', 'america', 'analysis', 'analytics', 'angel',
  'answer', 'anywhere', 'api', 'app', 'apparel', 'arc', 'arch', 'archive', 'area', 'arena',
  'ark', 'armor', 'army', 'around', 'art', 'artist', 'artists', 'arts', 'asset', 'assets',
  'assist', 'assistant', 'associates', 'association', 'atlanta', 'atlas', 'attack', 'attorney', 'audio', 'audit',
  'austin', 'authority', 'auto', 'automation', 'avenue', 'award', 'aware', 'away', 'axis', 'babe',
  'baby', 'back', 'backup', 'balance', 'ball', 'bamboo', 'banana', 'bang', 'bank', 'banking',
  'banks', 'banner', 'bar', 'bargain', 'barn', 'bars', 'base', 'basics', 'bay', 'beach',
  'beam', 'bean', 'bear', 'beast', 'beat', 'beauty', 'bed', 'bee', 'beer', 'bell',
  'bench', 'benefits', 'berry', 'best', 'bet', 'beta', 'bets', 'better', 'beyond', 'bid',
  'bids', 'big', 'bill', 'bin', 'bio', 'bird', 'bit', 'bite', 'bites', 'bits',
  'black', 'blast', 'bling', 'bliss', 'block', 'blocks', 'blue', 'board', 'boards', 'boat',
  'body', 'bomb', 'bond', 'bonus', 'book', 'booking', 'books', 'boom', 'boost', 'booster',
  'booth', 'boss', 'boston', 'bot', 'bots', 'bound', 'boutique', 'box', 'boxes', 'boy',
  'boys', 'brain', 'brains', 'brand', 'branding', 'brands', 'break', 'brew', 'bridge', 'bright',
  'bro', 'broker', 'brokers', 'brothers', 'bubble', 'bucket', 'bud', 'buddies', 'buddy', 'budget',
  'bug', 'build', 'builder', 'builders', 'building', 'bull', 'bunny', 'bureau', 'bus', 'business',
  'buster', 'butler', 'button', 'buy', 'buyer', 'buyers', 'buys', 'buzz', 'byte', 'bytes',
  'cab', 'cable', 'cache', 'cad', 'caddy', 'cafe', 'cake', 'call', 'calls', 'cam',
  'camera', 'camp', 'campus', 'cams', 'can', 'candy', 'canvas', 'cap', 'capital', 'car',
  'card', 'cards', 'care', 'career', 'careers', 'cargo', 'cars', 'cart', 'casa', 'case',
  'cases', 'cash', 'casino', 'cast', 'caster', 'casting', 'castle', 'cat', 'catalog', 'catering',
  'cats', 'cave', 'cell', 'center', 'centers', 'central', 'centric', 'ceo', 'chain', 'challenge',
  'champ', 'champion', 'change', 'channel', 'charge', 'chart', 'charter', 'charts', 'chase', 'chat',
  'chatter', 'cheap', 'check', 'checker', 'checks', 'chef', 'chem', 'chick', 'child', 'chip',
  'chips', 'choice', 'choices', 'circle', 'circles', 'city', 'clan', 'class', 'classic', 'clean',
  'cleaning', 'clear', 'click', 'clicks', 'clinic', 'clip', 'clips', 'clock', 'clothing', 'cloud',
  'clouds', 'club', 'clubs', 'coach', 'coaching', 'code', 'coder', 'codes', 'coin', 'coins',
  'collective', 'collector', 'college', 'color', 'colors', 'comet', 'comfort', 'commerce', 'commercial',
'communication', 'community', 'comp', 'companies', 'companion', 'company', 'compare', 'compass', 'complete',
'computer', 'concept', 'concepts', 'concierge', 'conference', 'connect', 'connection', 'connections',
'connector', 'construction', 'consult', 'consultancy', 'consultant', 'consultants', 'consulting', 'contact',
'contacts', 'content', 'contest', 'control', 'cook', 'cool', 'coop', 'cop', 'copy', 'core', 'corner',
'corp', 'corporation', 'corps', 'cosmetics', 'cost', 'count', 'counter', 'country', 'coupon', 'coupons',
'course', 'courses', 'court', 'couture', 'cove', 'cover', 'covers', 'cow', 'craft', 'craze', 'crazy',
'create', 'creation', 'creations', 'creative', 'creator', 'credit', 'credits', 'crew', 'critic', 'cross',
'crowd', 'cruise', 'crunch', 'crush', 'cube', 'culture', 'cup', 'cure', 'cut', 'cycle', 'dad', 'daily',
'dance', 'dash', 'dashboard', 'data', 'database', 'date', 'dating', 'day', 'days', 'deal', 'dealer',
'deck', 'decor', 'defense', 'deli', 'delight', 'delivery', 'deluxe', 'demo', 'den', 'dental', 'depot',
'design', 'designer', 'designers', 'designs', 'desk', 'detective', 'developer', 'development', 'devil',
'dial', 'diamond', 'diary', 'diet', 'dig', 'digest', 'digital', 'direct', 'director', 'discovery', 'dish',
'display', 'distribution', 'diva', 'diy', 'dj', 'dna', 'doc', 'dock', 'docs', 'doctor', 'dog', 'dollar',
'dome', 'door', 'dot', 'down', 'download', 'dragon', 'draw', 'dream', 'dreams', 'dress', 'drink', 'drive',
'driver', 'droid', 'drop', 'dude', 'dynamics', 'earth', 'ease', 'east', 'easy', 'edge', 'edit', 'editor',
'education', 'effect', 'egg', 'electric', 'elements', 'elite', 'email', 'empire', 'emporium', 'end',
'energy', 'engine', 'engineer', 'engineering', 'enterprise', 'enterprises', 'entertainment', 'equipment',
'equity', 'era', 'essentials', 'estate', 'etc', 'event', 'events', 'everything', 'evolution', 'exchange',
'experience', 'expert', 'experts', 'explorer', 'expo', 'express', 'extra', 'extreme', 'eye', 'eyes',
'fabric', 'face', 'fact', 'factor', 'factory', 'fail', 'fair', 'fairy', 'family', 'fan', 'fans', 'fantasy',
'fare', 'farm', 'farms', 'fashion', 'fast', 'feed', 'fest', 'fever', 'field', 'fight', 'file', 'files',
'filter', 'finance', 'financial', 'find', 'finder', 'finders', 'fire', 'firm', 'first', 'fish', 'fit',
'fitness', 'five', 'fix', 'flash', 'flex', 'flicks', 'flight', 'flip', 'flix', 'floor', 'flow', 'flower',
'flowers', 'fly', 'flyer', 'focus', 'folder', 'folio', 'food', 'foods', 'foot', 'force', 'forest', 'forever',
'forex', 'forge', 'form', 'forms', 'formula', 'fortune', 'forum', 'forward', 'foto', 'foundation', 'four',
'fox', 'frame', 'franchise', 'freak', 'freaks', 'free', 'freedom', 'frenzy', 'fresh', 'friend', 'friendly',
'friends', 'frog', 'front', 'fruit', 'fuel', 'full', 'fun', 'fund', 'funding', 'funds', 'fuse', 'fusion',
'future', 'gadget', 'gadgets', 'gain', 'gal', 'galaxy', 'gallery', 'game', 'gamer', 'games', 'gaming',
'gang', 'garage', 'garden', 'gas', 'gate', 'gateway', 'gator', 'gear', 'geek', 'geeks', 'gem', 'gems',
'gen', 'generation', 'generator', 'genie', 'genius', 'geo', 'get', 'giant', 'gift', 'gifts', 'gig', 'girl',
'glass', 'global', 'globe', 'go', 'goal', 'god', 'gold', 'good', 'goods', 'gourmet', 'grade', 'gram',
'graph', 'graphic', 'graphics', 'great', 'green', 'grid', 'groove', 'ground', 'group', 'groups', 'grow',
'guard', 'guide', 'guides', 'guild', 'gun', 'guru', 'guy', 'guys', 'gym', 'hack', 'hacker', 'hacks', 'hair',
'hall', 'hand', 'happy', 'hardware', 'harmony', 'hat', 'haven', 'hawk', 'head', 'heads', 'health',
'healthcare', 'heart', 'heat', 'heaven', 'hell', 'help', 'helper', 'here', 'hero', 'heroes', 'high', 'hill',
'hire', 'history', 'hit', 'hits', 'hive', 'holdings', 'home', 'homes', 'hood', 'hook', 'hop', 'hope',
'hopper', 'host', 'hosting', 'hot', 'hotel', 'hotels', 'hound', 'hour', 'house', 'houses', 'how', 'hq',
'hub', 'hunt', 'hunter', 'hunters', 'hut', 'hype', 'ice', 'icon', 'idea', 'ideas', 'image', 'images',
'imaging', 'impact', 'import', 'inbox', 'income', 'incorporated', 'index', 'industries', 'industry', 'info',
'information', 'ing', 'inn', 'innovation', 'innovations', 'ins', 'inside', 'insider', 'insight', 'insights',
'institute', 'insurance', 'insure', 'intelligence', 'interactive', 'interiors', 'international', 'internet',
'invest', 'investment', 'investments', 'investor', 'island', 'ist', 'jack', 'jam', 'jar', 'jazz', 'jeans',
'jet', 'jewelry', 'job', 'jobs', 'joe', 'journal', 'journey', 'joy', 'juice', 'jump', 'junction', 'jungle',
'junkie', 'junkies', 'junky', 'karma', 'kart', 'keeper', 'key', 'keys', 'kick', 'kid', 'kids', 'kin',
'king', 'kingdom', 'kings', 'kiosk', 'kiss', 'kit', 'kitchen', 'kits', 'knowledge', 'lab', 'label',
'labels', 'labs', 'lady', 'lake', 'land', 'lane', 'laser', 'launch', 'law', 'lawyer', 'lawyers', 'lead',
'leader', 'leaders', 'leads', 'leaf', 'league', 'learn', 'learning', 'lease', 'led', 'lee', 'legal', 'lens',
'ler', 'less', 'lessons', 'let', 'letter', 'level', 'life', 'lifestyle', 'lift', 'light', 'lighting',
'lights', 'like', 'limited', 'line', 'lines', 'link', 'links', 'lion', 'list', 'listing', 'listings', 'lists',
'lit', 'lite', 'live', 'living', 'llc', 'load', 'loan', 'loans', 'local', 'location', 'locator', 'lock',
'locker', 'lodge', 'loft', 'log', 'logic', 'login', 'logistics', 'logo', 'logos', 'logs', 'look', 'loop',
'lord', 'lot', 'lottery', 'lotto', 'lounge', 'love', 'lover', 'lovers', 'luck', 'lux', 'luxury', 'machine',
'machines', 'mad', 'made', 'madness', 'mafia', 'mag', 'magazine', 'magic', 'magnet', 'mail', 'mailer',
'make', 'maker', 'makers', 'mall', 'mama', 'man', 'manage', 'management', 'manager', 'mania', 'maniac',
'manual', 'map', 'maps', 'marine', 'mark', 'market', 'marketing', 'marketplace', 'markets', 'marks', 'mart',
'mash', 'mass', 'massage', 'master', 'masters', 'mat', 'match', 'mate', 'mates', 'math', 'matic', 'matrix',
'matter', 'matters', 'maven', 'max', 'media', 'medic', 'medical', 'medicine', 'meet', 'meeting', 'meme',
'memo', 'memory', 'men', 'mentor', 'menu', 'merchant', 'mesh', 'message', 'messenger', 'metal', 'meter',
'method', 'metrics', 'metrix', 'metro', 'mex', 'micro', 'miles', 'mill', 'mind', 'minder', 'minds', 'mine',
'mint', 'mirror', 'mission', 'mix', 'mixer', 'mob', 'mobile', 'mobility', 'mod', 'mode', 'model', 'models',
'mojo', 'mom', 'moms', 'money', 'monitor', 'monkey', 'monster', 'monsters', 'moon', 'more', 'mortgage',
'motion', 'moto', 'motor', 'motors', 'mountain', 'mouse', 'move', 'movement', 'movers', 'moves',
'multimedia', 'muse', 'museum', 'music', 'name', 'names', 'nation', 'nature', 'navi', 'navigator', 'needs',
'nerd', 'ness', 'nest', 'net', 'nets', 'network', 'networking', 'networks', 'new', 'news', 'newsletter',
'next', 'nexus', 'nic', 'nice', 'night', 'nine', 'ninja', 'node', 'north', 'note', 'notes', 'nova', 'now',
'nut', 'nutrition', 'nuts', 'oasis', 'ocean', 'offer', 'offers', 'office', 'ography', 'oil', 'ology', 'one',
'online', 'only', 'opia', 'opolis', 'ops', 'option', 'options', 'orama', 'orange', 'order', 'org',
'organic', 'organizer', 'outlet', 'over', 'owl', 'ox', 'pac', 'pack', 'package', 'packs', 'pad', 'pads',
'page', 'pages', 'paint', 'painting', 'pak', 'pal', 'palace', 'pals', 'pan', 'panda', 'panel', 'paper',
'papers', 'paradise', 'park', 'parking', 'part', 'parties', 'partner', 'partners', 'parts', 'party', 'pass',
'passion', 'patch', 'path', 'patrol', 'pay', 'payment', 'payments', 'peak', 'pedia', 'pen', 'people',
'perfect', 'performance', 'perks', 'pet', 'pets', 'pharma', 'pharmacy', 'phone', 'phones', 'photo',
'photography', 'photos', 'pic', 'pick', 'picks', 'pics', 'picture', 'pictures', 'pie', 'pig', 'pilot', 'pin',
'ping', 'pink', 'pipe', 'pit', 'pix', 'pixel', 'pixels', 'pizza', 'place', 'places', 'plan', 'planet',
'planner', 'planning', 'plans', 'plant', 'plate', 'platform', 'play', 'player', 'plaza', 'please', 'plex',
'plug', 'plus', 'pocket', 'pod', 'podcast', 'point', 'points', 'poker', 'politics', 'poll', 'pon', 'pond',
'pool', 'pop', 'port', 'portal', 'portfolio', 'pos', 'post', 'poster', 'posters', 'posts', 'pot', 'power',
'premium', 'prep', 'press', 'preview', 'price', 'prices', 'pride', 'prime', 'print', 'printer', 'printing',
'prints', 'prize', 'process', 'prod', 'product', 'production', 'productions', 'products', 'professional',
'professionals', 'professor', 'profile', 'profiles', 'profit', 'profits', 'program', 'programs', 'project',
'projects', 'promo', 'promos', 'promotion', 'promotions', 'proof', 'properties', 'property', 'pros',
'protect', 'protection', 'provider', 'proxy', 'pub', 'public', 'publications', 'publishing', 'pulse',
'pump', 'punch', 'punk', 'puppy', 'push', 'quality', 'queen', 'quest', 'questions', 'quick', 'quiz',
'quote', 'quotes', 'rabbit', 'race', 'racing', 'rack', 'radar', 'radio', 'rain', 'ranch', 'rank',
'ranking', 'rap', 'rat', 'rate', 'rates', 'rating', 'ray', 'reach', 'read', 'reader', 'ready', 'real',
'realestate', 'reality', 'realty', 'recipe', 'recipes', 'record', 'records', 'recovery', 'recruitment',
'red', 'reference', 'reg', 'register', 'registry', 'relief', 'rent', 'rental', 'rentals', 'rep', 'repair',
'report', 'reporter', 'reports', 'republic', 'res', 'rescue', 'research', 'resort', 'resource',
'resources', 'response', 'restaurant', 'results', 'resume', 'retail', 'retro', 'rev', 'review', 'reviews',
'revolution', 'reward', 'rewards', 'rex', 'rich', 'ride', 'rider', 'right', 'ring', 'rise', 'risk', 'rite',
'river', 'road', 'robot', 'rock', 'rocket', 'rocks', 'roll', 'room', 'rooms', 'root', 'rose', 'roulette',
'route', 'rules', 'run', 'runner', 'rush', 'safari', 'safe', 'safety', 'sage', 'sale', 'sales', 'salon',
'sat', 'save', 'saver', 'savers', 'savings', 'savvy', 'say', 'scale', 'scan', 'scanner', 'scape',
'scapes', 'scene', 'school', 'schools', 'science', 'scoop', 'scope', 'score', 'scout', 'screen',
'scribe', 'script', 'scripts', 'sea', 'seal', 'search', 'secret', 'secrets', 'secure', 'security', 'see',
'seed', 'seek', 'seeker', 'select', 'selection', 'sell', 'seller', 'selling', 'send', 'senior', 'sense',
'seo', 'series', 'serv', 'serve', 'server', 'servers', 'service', 'services', 'set', 'seven', 'sexy',
'shgroup', 'shack', 'share', 'shares', 'sharing', 'shark', 'shed', 'sheet', 'shelf', 'shell', 'shield',
'shift', 'shine', 'ship', 'shirt', 'shirts', 'shoe', 'shoes', 'shop', 'shopper', 'shopping', 'shot',
'shots', 'show', 'showcase', 'shows', 'side', 'sight', 'sign', 'signal', 'signs', 'silver', 'simple',
'singles', 'sit', 'site', 'sites', 'six', 'ski', 'skill', 'skills', 'skin', 'skins', 'sky', 'slot', 'small',
'smart', 'smarts', 'smile', 'smith', 'sms', 'snap', 'snet', 'snow', 'soccer', 'social', 'socialmedia',
'society', 'soft', 'software', 'sol', 'solar', 'solution', 'solutions', 'son', 'song', 'songs', 'sonic',
'soul', 'sound', 'sounds', 'soup', 'source', 'sources', 'sourcing', 'south', 'spa', 'space', 'spaces',
'span', 'spark', 'speak', 'spec', 'special', 'specialist', 'specialists', 'specials', 'speed', 'sphere',
'spider', 'spin', 'spirit', 'splash', 'splus', 'sport', 'sports', 'spot', 'spots', 'spring', 'spy', 'squad',
'square', 'squared', 'stack', 'staff', 'staffing', 'stage', 'stamp', 'stand', 'star', 'stars', 'start',
'starter', 'stat', 'state', 'station', 'stats', 'status', 'steel', 'step', 'steps', 'ster', 'stick',
'stickers', 'stock', 'stocks', 'stone', 'stop', 'storage', 'store', 'stores', 'stories', 'storm', 'story',
'strategies', 'strategy', 'stream', 'streaming', 'streams', 'street', 'strong', 'student', 'studio',
'studios', 'study', 'stuff', 'style', 'styles', 'success', 'sugar', 'suite', 'summit', 'sun', 'super',
'superstore', 'supplier', 'supplies', 'supply', 'support', 'sure', 'surf', 'surfer', 'surfing', 'survey',
'surveys', 'swag', 'swap', 'sweet', 'switch', 'synergy', 'sys', 'system', 'systems', 'tab', 'table',
'tablet', 'tag'

]
};